"use client";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/Sidebar";
import AuthGuard from "@/components/AuthGuard";
import { db } from "@/lib/firebase";
import { collection, doc, onSnapshot, query, setDoc, where } from "firebase/firestore";
import { IndianRupee, Search, WalletCards, CheckCircle2 } from "lucide-react";

type Person={id:string;type:"labour"|"staff";name:string;mobile:string;monthlySalary:number;active:boolean};
type Attendance={personId:string;personType:"labour"|"staff";date:string;status:"Present"|"Absent"|"Half Day";overtimeHours?:number};
type Adjustments={advance:number;deduction:number;paid:boolean};
function monthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function daysInMonth(key:string){const [y,m]=key.split("-").map(Number);return new Date(y,m,0).getDate()}
function sundayCountInMonth(key:string){const [y,m]=key.split("-").map(Number);const total=new Date(y,m,0).getDate();let count=0;for(let day=1;day<=total;day++){const d=new Date(y,m-1,day);if(d.getDay()===0)count++}return count}
function workingDaysInMonth(key:string){const [y,m]=key.split("-").map(Number);const total=new Date(y,m,0).getDate();let count=0;for(let day=1;day<=total;day++){const d=new Date(y,m-1,day);if(d.getDay()!==0)count++}return count}
function isWorkingDate(date:string){const d=new Date(`${date}T00:00:00`);return d.getDay()!==0}
function monthStartEnd(key:string){const [y,m]=key.split("-").map(Number);const end=new Date(y,m,0).getDate();return{start:`${key}-01`,end:`${key}-${String(end).padStart(2,"0")}`}}
export default function SalaryPage(){
 const [people,setPeople]=useState<Person[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[month,setMonth]=useState(monthKey()),[search,setSearch]=useState(""),[adjustments,setAdjustments]=useState<Record<string,Adjustments>>({}),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState("");
 useEffect(()=>{const a=onSnapshot(collection(db,"labour"),snap=>{const rows=snap.docs.map(d=>{const x=d.data() as any;return{id:d.id,type:"labour" as const,name:x.name||"",mobile:x.mobile||"",monthlySalary:Number(x.monthlySalary||0),active:x.active!==false}});setPeople(prev=>[...rows,...prev.filter(p=>p.type==="staff")])},e=>setError(e.message));const b=onSnapshot(collection(db,"staff"),snap=>{const rows=snap.docs.map(d=>{const x=d.data() as any;return{id:d.id,type:"staff" as const,name:x.name||"",mobile:x.mobile||"",monthlySalary:Number(x.monthlySalary||0),active:x.active!==false}});setPeople(prev=>[...prev.filter(p=>p.type==="labour"),...rows])},e=>setError(e.message));return()=>{a();b()}},[]);
 useEffect(()=>{const {start,end}=monthStartEnd(month);const q=query(collection(db,"attendance"),where("date",">=",start),where("date","<=",end));return onSnapshot(q,snap=>setAttendance(snap.docs.map(d=>d.data() as Attendance)),e=>setError(e.message))},[month]);
 const activePeople=useMemo(()=>people.filter(p=>p.active&&`${p.name} ${p.mobile}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)),[people,search]);
 const salaryDays=daysInMonth(month);
 const sundayCount=sundayCountInMonth(month);
 function stats(p:Person){const rows=attendance.filter(a=>a.personId===p.id&&a.personType===p.type),regularRows=rows.filter(a=>isWorkingDate(a.date)),sundayRows=rows.filter(a=>!isWorkingDate(a.date)&&p.type==="labour"&&a.status!=="Absent"),present=regularRows.filter(a=>a.status==="Present").length,absent=regularRows.filter(a=>a.status==="Absent").length,half=regularRows.filter(a=>a.status==="Half Day").length,payableDays=present+half*.5,dayRate=salaryDays?Number(p.monthlySalary||0)/salaryDays:0,regularEarned=dayRate*payableDays,sundayEarned=sundayRows.reduce((sum,a)=>sum+dayRate*(a.status==="Half Day"?.5:1)*2,0),overtimeHours=rows.reduce((sum,a)=>sum+Number(a.overtimeHours||0),0),hourlyRate=dayRate/8,overtimeEarned=hourlyRate*overtimeHours,earned=Math.round(regularEarned+sundayEarned+overtimeEarned),a=adjustments[`${p.type}_${p.id}`]||{advance:0,deduction:0,paid:false},advance=Number(a.advance||0),deduction=Number(a.deduction||0),net=earned-advance-deduction;return{present,absent,half,payableDays,dayRate,regularEarned,sundayRows:sundayRows.length,sundayEarned,overtimeHours,overtimeEarned,earned,advance,deduction,net,paid:a.paid}}
 function update(p:Person,patch:Partial<Adjustments>){const key=`${p.type}_${p.id}`;setAdjustments(prev=>({...prev,[key]:{...{advance:0,deduction:0,paid:false},...(prev[key]||{}),...patch}}))}
 async function save(p:Person){const s=stats(p),key=`${p.type}_${p.id}`;setSaving(key);setError("");try{await setDoc(doc(db,"salary",`${month}_${p.type}_${p.id}`),{month,personId:p.id,personType:p.type,personName:p.name,monthlySalary:p.monthlySalary,salaryDays,sundayCount,presentDays:s.present,absentDays:s.absent,halfDays:s.half,payableDays:s.payableDays,sundayWorkDays:s.sundayRows,sundayDoublePay:s.sundayEarned,overtimeHours:s.overtimeHours,overtimePay:s.overtimeEarned,earnedSalary:s.earned,advance:s.advance,deduction:s.deduction,netSalary:s.net,balance:s.net,paid:s.paid,updatedAt:new Date().toISOString()})}catch(e:any){setError(e?.message||"Unable to save salary")}finally{setSaving(null)}}
 const totals=activePeople.reduce((a,p)=>{const s=stats(p);a.monthly+=p.monthlySalary;a.net+=s.net;a.paid+=s.paid?Math.max(0,s.net):0;a.unpaid+=s.paid?0:Math.max(0,s.net);return a},{monthly:0,net:0,paid:0,unpaid:0});
 return <AuthGuard allowedRoles={["admin"]}><div style={{display:"flex",minHeight:"100vh"}}><Sidebar/><main style={{flex:1,padding:"30px 34px",minWidth:0}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20,marginBottom:22}}><div><div style={{color:"#168f67",fontWeight:800,fontSize:12,letterSpacing:2}}>SMC MANAGEMENT</div><h1 style={{margin:"6px 0",color:"#082b68",fontSize:30}}>Salary Management</h1><p style={{margin:0,color:"#6d7d96"}}>Calculate salary from monthly pay and attendance.</p></div><div style={{display:"flex",alignItems:"center",gap:10}}><label style={{color:"#52627b",fontWeight:700}}>Month</label><input className="input" style={{width:155}} type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:18}}>{[['Active People',activePeople.length,'#1266e8',WalletCards],['Monthly Salary',totals.monthly,'#168f67',IndianRupee],['Net Payable',totals.net,'#082b68',IndianRupee],['Unpaid',totals.unpaid,'#c93636',WalletCards]].map(([label,value,color,Icon]:any)=><div className="card" key={label} style={{padding:18,display:"flex",alignItems:"center",gap:12}}><div style={{width:42,height:42,borderRadius:12,background:"#edf4ff",color,display:"grid",placeItems:"center"}}><Icon size={20}/></div><div><div style={{color:"#71809a",fontSize:12,fontWeight:700}}>{label}</div><b style={{display:"block",marginTop:4,color:"#17345f",fontSize:22}}>{label==="Active People"?value:`₹ ${Number(value).toLocaleString("en-IN")}`}</b></div></div>)}</div>
  <div style={{display:"flex",gap:12,marginBottom:16,alignItems:"center"}}><div style={{position:"relative",width:330,maxWidth:"100%"}}><Search size={17} style={{position:"absolute",left:12,top:12,color:"#7b8ca5"}}/><input className="input" style={{paddingLeft:38}} placeholder="Search name or mobile" value={search} onChange={e=>setSearch(e.target.value)}/></div><div style={{color:"#71809a",fontSize:12}}>Rules: Monthly salary ÷ calendar days • Present = 1 day • Half Day = 0.5 • Absent = 0 • Labour Sunday = 2× • OT is calculated automatically from In/Out time • Advance can make balance negative.</div></div>
  {error&&<div style={{background:"#fff1f1",border:"1px solid #f0caca",color:"#b42318",padding:12,borderRadius:10,marginBottom:16,fontSize:13}}>{error}</div>}
  <div className="card" style={{padding:20,overflowX:"auto"}}><h2 style={{margin:"0 0 15px",color:"#17345f",fontSize:18}}>Salary Sheet — {month}</h2><table style={{width:"100%",borderCollapse:"collapse",minWidth:980}}><thead><tr style={{textAlign:"left",color:"#71809a",fontSize:11,borderBottom:"1px solid #e8eef7"}}>{['Name','Type','Monthly','P','A','½','Earned','Advance','Deduction','Net / Balance','Status','Action'].map(h=><th key={h} style={{padding:"11px 8px"}}>{h}</th>)}</tr></thead><tbody>{activePeople.length===0?<tr><td colSpan={12} style={{padding:45,textAlign:"center",color:"#71809a"}}>No active Labour or Staff records.</td></tr>:activePeople.map(p=>{const s=stats(p),key=`${p.type}_${p.id}`;return <tr key={key} style={{borderBottom:"1px solid #eef2f7"}}><td style={{padding:12,fontWeight:800,color:"#17345f"}}>{p.name}</td><td style={{padding:12}}>{p.type==="labour"?"Labour":"Staff"}</td><td style={{padding:12,fontWeight:700}}>₹ {p.monthlySalary.toLocaleString("en-IN")}</td><td style={{padding:12,color:"#168f67",fontWeight:700}}>{s.present}</td><td style={{padding:12,color:"#c93636",fontWeight:700}}>{s.absent}</td><td style={{padding:12,color:"#b7791f",fontWeight:700}}>{s.half}</td><td style={{padding:12,fontWeight:800}}>₹ {s.earned.toLocaleString("en-IN")}</td><td style={{padding:8}}><input className="input" style={{width:105}} type="number" min="0" value={s.advance||""} onChange={e=>update(p,{advance:Number(e.target.value||0)})}/></td><td style={{padding:8}}><input className="input" style={{width:105}} type="number" min="0" value={s.deduction||""} onChange={e=>update(p,{deduction:Number(e.target.value||0)})}/></td><td style={{padding:12,fontWeight:800,color:s.net<0?"#c93636":"#082b68"}}>₹ {s.net.toLocaleString("en-IN")}{s.net<0&&<div style={{fontSize:10,color:"#c93636",marginTop:3}}>Advance balance due</div>}</td><td style={{padding:8}}><button onClick={()=>update(p,{paid:!s.paid})} style={{border:0,background:s.paid?"#e8f8ef":"#fff5e8",color:s.paid?"#168f67":"#b7791f",padding:"7px 10px",borderRadius:20,fontWeight:800,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:5}}>{s.paid&&<CheckCircle2 size={14}/>} {s.paid?"Paid":"Unpaid"}</button></td><td style={{padding:8}}><button className="btn btn-primary" disabled={saving===key} onClick={()=>save(p)}>{saving===key?"Saving…":"Save"}</button></td></tr>})}</tbody></table></div>
 </main></div></AuthGuard>
}
